### ISSUE TITLE
낙타 찾기 게임시작시간 재조정

### ISSUE THREAD

**Issue by Su-Kyung** [Su-Kyung/RemedyFriends-ver.2#21]
게임 시작 신호 로직이 전체적으로 하나의 스크립트에서 관리되고 있는데
해당 스크립트를 수정하면서 시작 시점이 변경되었으니
낙타찾기에서 1초 미뤄뒀던거 복구시켜주세요~~
(복구되면 이슈 닫으면됩니다!)

이제 자동으로 시작! 이미지 사라진 뒤에 게임 시작됩니다.

**Comment by jjym12** [comment]
확인했슴다!
잘된다! (๑˃̵ᴗ˂̵)و ♡
